language: php
sudo: false
php:
  - 7.0
  - 7.1

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer update --no-scripts

script:
  - vendor/bin/phpunit

after_success:
  - vendor/bin/test-reporter

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: always
    on_failure: always